import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {renderHome} from './src/home.mjs';
import {renderSocialLinks} from './src/socials.mjs';
import {renderStory} from './src/story.mjs';
import {createSEO} from './src/seo.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const out=root;
const site=JSON.parse(fs.readFileSync(path.join(root,'site.config.json'),'utf8'));
const navigationBoot=fs.readFileSync(path.join(root,'src/navigation.js'),'utf8').replace(/<\/script/gi,'<\\/script');
const pageProgress=`<div id="page-progress" class="page-progress" role="progressbar" aria-label="Loading page" aria-hidden="true" hidden><span></span></div><script>${navigationBoot}</script>`;
const research=JSON.parse(fs.readFileSync(path.join(root,'src/research.json'),'utf8').replace(/^\uFEFF/,''));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=[
 {slug:'seeds-and-mixes',name:'Seeds & seed mixes',short:'A handful of goodness.',description:'A little crunch for breakfast bowls, snacks and everything in between.',image:'TB-15',match:'Seeds & Seed Mixes'},
 {slug:'kitchen-staples',name:'Kitchen staples',short:'Familiar flavours. Everyday favourites.',description:'Nolen gur, ghee and turmeric for the recipes you come back to.',image:'TB-12',match:'Kitchen Staples'},
 {slug:'juices-and-beverages',name:'Juices & beverages',short:'Take a refreshing pause.',description:'Fruit blends and Bengali-inspired flavours, bottled for your day.',image:'TB-11',match:'Juices & Beverages'},
 {slug:'breakfast-and-drink-mixes',name:'Breakfast & drink mixes',short:'Make a little time for yourself.',description:'Discover a sattu blend for your daily drink routine.',image:'TB-02',match:'Breakfast & Drink Mixes'},
 {slug:'supplements-and-fibre',name:'Supplements & fibre',short:'Explore your daily essentials.',description:'Discover moringa capsules and isabgol. Always follow the product label.',image:'TB-01',match:'Supplements & Fibre'}
];
// Product copy is intentionally limited to identity, flavour and culinary use.
// Research records retain unresolved retailer metadata for the owner to review.
const content={
 'TB-01':['moringa-capsules','Moringa Capsules','30 capsules','Moringa in a convenient capsule format. Read the product label for ingredients, directions and suitability.','Use only as directed on the pack. Check the product label before use.'],
 'TB-02':['sattu-protein-mix','Sattu Protein Mix','50 g','An easy-to-mix sattu and seed blend for your everyday drink routine.','Prepare with water or milk, following the quantities and directions on the pack.'],
 'TB-04':['isabgol','Isabgol Psyllium Husk','100 g','Psyllium husk in a resealable pack. Check the product label for preparation and serving directions.','Follow the pack directions, including the recommended amount of liquid.'],
 'TB-05':['healthy-mix','Healthy Mix','200 g','Pumpkin, sunflower, flax and sesame seeds come together in one versatile blend. A little texture for the things you love to eat.','Sprinkle over breakfast bowls, yogurt and salads. Store as directed on the pack. Contains sesame.'],
 'TB-06':['nolen-gur-coconut-chill','Nolen Gur Coconut Chill','200 ml','Coconut meets the familiar sweetness of nolen gur in a Bengali-inspired bottled drink.','Serve chilled. Shake gently before opening and follow the storage instructions on the bottle.'],
 'TB-07':['mosambi-lemon-juice','Mosambi & Lemon Juice','100 ml','A citrus combination of mosambi and lemon for a refreshing moment in your day.','Follow the serving and refrigeration instructions on the bottle.'],
 'TB-08':['pineapple-fruit-beer-juice','Pineapple Fruit Beer Juice','200 ml','Discover the pineapple variety in the TreeBites Fruit Beer Juice range.','Check the bottle for ingredients, preparation and storage instructions.'],
 'TB-09':['watermelon-fruit-beer-juice','Watermelon Fruit Beer Juice','100 ml','Discover the watermelon variety in the TreeBites Fruit Beer Juice range.','Check the bottle for ingredients, preparation and storage instructions.'],
 'TB-10':['carrot-apple-fruit-beer-juice','Carrot & Apple Fruit Beer Juice','100 ml','Carrot and apple come together in this bottled blend from the TreeBites Fruit Beer Juice range.','Check the bottle for ingredients, preparation and storage instructions.'],
 'TB-11':['carrot-beetroot-ginger-lemon','Carrot, Beetroot, Ginger & Lemon','100 ml','A colourful juice combination of carrot, beetroot, ginger and lemon.','Follow the serving and refrigeration instructions on the bottle.'],
 'TB-12':['nolen-gur','Nolen Gur','250 g','Bengali date palm jaggery, with its distinctive sweetness. Bring a familiar flavour to desserts, drinks and everyday recipes.','Use in payesh, desserts or drinks to taste. Follow storage instructions on the jar.'],
 'TB-13':['flax-seeds','Flax Seeds','250 g','A versatile pantry addition with a subtly nutty flavour. Explore new ways to enjoy your breakfast bowls and bakes.','Use according to the pack directions. Store in a cool, dry place and reseal after opening.'],
 'TB-14':['chia-seeds','Chia Seeds','250 g','Small seeds for your daily rituals. Add soaked chia to breakfast bowls, smoothies and yogurt.','Soak before consumption, following the pack directions. Store as instructed on the label.'],
 'TB-15':['pumpkin-seeds','Pumpkin Seeds','250 g','A satisfying crunch for salads, breakfast bowls and your favourite recipes.','Enjoy according to the pack directions. Reseal after opening and store as instructed.'],
 'TB-16':['sunflower-seeds','Sunflower Seeds','250 g','A pantry staple for adding texture to salads, bakes and everyday meals.','Use according to the pack directions. Store in a cool, dry place and reseal after opening.'],
 'TB-17':['pure-ghee','Pure Ghee','250 g','Traditional clarified butter for your everyday kitchen. Add its rich flavour to warm rice, rotis and favourite recipes.','Use in cooking or add to warm food to taste. Contains milk. Follow the storage instructions on the jar.'],
 'TB-18':['raw-turmeric','Raw Turmeric · Kacchi Haldi','200 g','Raw turmeric for the kitchen. Bring its distinctive colour and flavour to your everyday cooking.','Wash and prepare before use. Follow the storage instructions provided with the product.'],
 'TB-19':['sattu-protein-mix-150g','Sattu Protein Mix · 150 g','150 g','A larger pack of TreeBites Sattu Protein Mix for your breakfast and drink routine.','Prepare according to the directions on the pack. Check the label for the complete ingredient list.'],
 'TB-20':['shilajit-capsules','Shilajit Capsules','30 capsules','Shilajit in a capsule format. Check the complete product label for ingredients, directions and suitability.','Use only as directed on the pack. Read all label precautions before use.']
};
const cleanImages=new Set(['TB-12','TB-13','TB-14','TB-15','TB-16','TB-17']);
const packConflicts=new Set(['TB-05','TB-07','TB-08','TB-12']);
const products=research.products.filter(r=>Object.hasOwn(content,r.researchId)).map(r=>{const c=content[r.researchId];const live=JSON.parse(fs.readFileSync(path.join(root,'src',r.researchId+'.json'),'utf8'));return {...r,id:r.researchId,slug:c[0],name:c[1],size:c[2],description:c[3],use:c[4],category:categories.find(x=>x.match===r.proposedCategory),image:`/assets/${r.researchId}-${cleanImages.has(r.researchId)?'detail':'pack'}.png`,alternate:`/assets/${r.researchId}-pack.png`,website:live.url?`https://fashinoworld.com${live.url}`:r.fashinoworld.url,amazonURL:packConflicts.has(r.researchId)?null:r.amazon.url,packConflict:packConflicts.has(r.researchId)}});
// Conflicting Amazon pack variants deliberately do not get an active order link.
// Correct the source evidence before enabling any of these four links.
const pById=id=>products.find(p=>p.id===id);
const seo=createSEO({root,products,categories,site});
const favicon='/assets/Treebites_favicon.png';
const wordmark=`<span class="wordmark brand-logo"><img src="/assets/Treebites_logo.png" alt="TreeBites" width="1080" height="1080" decoding="async"></span>`;
const header=active=>`<a class="skip-link" href="#main">Skip to content</a><div class="announcement">Nourishing roots. Enriching lives.</div><header class="site-header"><a href="/" aria-label="TreeBites home">${wordmark}</a><button class="mobile-toggle" aria-expanded="false" aria-controls="main-nav" aria-label="Open navigation"><span></span><span></span></button><nav id="main-nav" aria-label="Main navigation">${[['Home','/','home'],['All products','/products/','products'],['Categories','/categories/','categories'],['Our story','/our-story/','story']].map(([name,href,key])=>`<a href="${href}"${key===active?' class="active" aria-current="page"':''}>${name}</a>`).join('')}</nav><a class="button small" href="/products/">Explore products</a></header>`;
const footer=()=>`<footer><div class="footer-main"><div><a href="/" aria-label="TreeBites home">${wordmark}</a><p>Little things. Everyday goodness.</p>${renderSocialLinks(site)}</div><div><h3>Explore</h3><a href="/products/">All products</a><a href="/categories/">Categories</a><a href="/our-story/">Our story</a><a href="/#questions">Your questions</a><a href="/sitemap/">Sitemap</a></div><div><h3>Our collection</h3>${categories.map(c=>`<a href="/categories/${c.slug}/">${esc(c.name)}</a>`).join('')}</div><div><h3>Say hello</h3><p>We’d love to hear from you.</p><a href="mailto:contact.fashino@gmail.com">contact.fashino@gmail.com</a><span>Kolkata, India</span></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} TreeBites.</span><span>Orders, payments and delivery are handled by your chosen retailer.</span></div></footer>`;
const layout=(title,description,body,active='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#203c2a"><title>${esc(title)} | TreeBites</title><meta name="description" content="${esc(description)}"><link rel="icon" type="image/png" href="${esc(favicon)}"><link rel="stylesheet" href="/assets/style.css"><script src="/assets/site.js" defer></script></head><body>${pageProgress}${header(active)}<main id="main">${body}</main>${footer()}</body></html>`;
function addStyles(html){
 if(html.includes('class="story-page"'))html=html.replace('</head>','<link rel="stylesheet" href="/assets/story.css"></head>');
 if(html.includes('class="section categories-full"'))html=html.replace('</head>','<link rel="stylesheet" href="/assets/collections.css"></head>');
 return html.replace('</head>','<link rel="stylesheet" href="/assets/pages.css"><link rel="stylesheet" href="/assets/brand.css"><link rel="stylesheet" href="/assets/motion.css"><noscript><style>@media(max-width:650px){.site-header{height:auto;flex-wrap:wrap;padding-top:18px}.mobile-toggle{display:none}.site-header nav{display:flex;position:static;flex-direction:row;flex-wrap:wrap;width:100%;padding:10px 0;border:0;box-shadow:none}.site-header nav a{width:auto;margin-right:18px}}</style></noscript></head>')}
function write(route,html){const folder=path.join(out,route);fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'index.html'),seo.decorate(addStyles(html),route?`/${route}/`:'/'))}
const card=p=>`<article class="product-card" data-category="${p.category.slug}" data-name="${esc((p.name+' '+p.category.name).toLowerCase())}"><a class="product-image${cleanImages.has(p.id)||p.id==='TB-05'?' clean':''}" href="/products/${p.slug}/"><img src="${p.image}" alt="TreeBites ${esc(p.name)}" width="900" height="900" loading="lazy" decoding="async"><span class="pack-tag">${esc(p.size)}</span></a><span class="eyebrow">${esc(p.category.name)}</span><h3><a href="/products/${p.slug}/">${esc(p.name)}</a></h3><a class="card-link" href="/products/${p.slug}/">View product<span class="sr-only">: ${esc(p.name)}</span></a></article>`;
const categoryTile=c=>{const p=pById(c.image);const n=products.filter(p=>p.category.slug===c.slug).length;return `<a class="category-tile" href="/categories/${c.slug}/"><div class="category-art"><img src="${p.image}" alt="${esc(c.name)} by TreeBites" loading="lazy" width="900" height="900"></div><div class="category-title"><h3>${esc(c.name)}</h3><span>${String(n).padStart(2,'0')} products</span></div></a>`};
const faq=`<section class="section faq-section" id="questions"><div><span class="eyebrow">A FEW THINGS TO KNOW</span><h2>Good questions.<br>Simple answers.</h2></div><div class="faq-list"><details><summary>How do I order a TreeBites product?</summary><p>Choose a product and select “Order on Amazon” or “Buy now”. Your chosen retailer opens in a new tab, where you can check the price, delivery and place your order.</p></details><details><summary>Where can I see the latest price?</summary><p>Visit the product’s Amazon or Fashinoworld page for the current price, offers and availability. These can vary between retailers.</p></details><details><summary>Where can I find ingredients and storage details?</summary><p>Check the product packaging and the retailer’s listing for the complete ingredient list, allergens, serving directions and storage instructions before ordering.</p></details><details><summary>Who handles delivery and returns?</summary><p>The retailer you order from handles payment, shipping, order support and returns. Their terms apply to your purchase.</p></details></div></section>`;
const home=renderHome({card,pById,categories,categoryTile,faq,productCount:products.length});
write('',layout('Seeds, Nolen Gur, Ghee & Everyday Goodness','Discover TreeBites seeds, kitchen staples, drinks and everyday nutrition. Browse the collection and order through Amazon or Fashinoworld.',home,'home'));
write('our-story',layout('Our Story & About the Brand','Meet TreeBites: our food and nutrition range, Bengali-inspired flavours, product information, where to buy and ways to contact the brand.',renderStory({categories,products,site}),'story'));
const chips=active=>`<nav class="category-chips" aria-label="Product categories"><a href="/products/"${!active?' aria-current="page" class="selected"':''}>All products</a>${categories.map(c=>`<a href="/categories/${c.slug}/"${active===c.slug?' aria-current="page" class="selected"':''}>${esc(c.name)}</a>`).join('')}</nav>`;
function collection(c){const list=c?products.filter(p=>p.category.slug===c.slug):products;return `<section class="collection-top"><div class="breadcrumbs"><a href="/">Home</a><span>/</span>${c?'<a href="/categories/">Categories</a><span>/</span>':''}<span>${c?esc(c.name):'All products'}</span></div><span class="eyebrow">THE TREEBITES COLLECTION</span><h1>${c?esc(c.name):'Good things. All in one place.'}</h1><p>${c?esc(c.description):'Explore everyday ingredients, familiar flavours and your next pantry favourite.'}</p></section><section class="section catalogue">${chips(c?.slug)}<div class="catalogue-tools"><p class="result-count" aria-live="polite">${list.length} products</p><label class="search-field"><span class="sr-only">Search ${c?esc(c.name):'all products'}</span><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg><input id="product-search" type="search" placeholder="Find your favourite…" autocomplete="off"></label></div><div class="product-grid catalogue-grid">${list.map(card).join('')}</div><div class="empty-state" hidden><h2>No products found.</h2><p>Try a different ingredient or product name.</p><button class="button outline" id="clear-search">Clear search</button></div></section>`}
write('products',layout('All products',`Browse all ${products.length} TreeBites products, from seeds and kitchen staples to juices and drink mixes.`,collection(),'products'));
write('categories',layout('Explore the collection','Discover five TreeBites categories: seeds, kitchen staples, beverages, drink mixes, supplements and fibre.',`<section class="collection-top"><div class="breadcrumbs"><a href="/">Home</a><span>/</span><span>Categories</span></div><span class="eyebrow">EXPLORE BY CATEGORY</span><h1>Find your kind of good.</h1><p>From your morning ritual to the recipes that feel like home.</p></section><section class="section categories-full">${categories.map((c,i)=>`<a class="category-row" href="/categories/${c.slug}/"><span class="category-number">0${i+1}</span><div class="category-row-copy"><span class="eyebrow">${esc(c.name)}</span><h2>${esc(c.short)}</h2><p>${esc(c.description)}</p><span class="text-link">Explore ${products.filter(p=>p.category.slug===c.slug).length} products</span></div><img src="${pById(c.image).image}" alt="${esc(c.name)} collection" loading="lazy" width="900" height="900"></a>`).join('')}</section>`,'categories'));
for(const c of categories)write(`categories/${c.slug}`,layout(c.name,c.description,collection(c),'categories'));
for(const p of products){const related=products.filter(x=>x.id!==p.id&&x.category.slug===p.category.slug);const relatedFinal=[...related,...products.filter(x=>x.id!==p.id&&!related.includes(x))].slice(0,4);const variants=`<div class="pack-options"><span class="eyebrow">PACK SIZE</span><span class="pack-option selected">${esc(p.size)}</span></div>`;
 const amazon=p.amazonURL?`<a class="button amazon" href="${esc(p.amazonURL)}" target="_blank" rel="noopener noreferrer">Order on Amazon<span class="sr-only"> (opens in a new tab)</span></a>`:`<button class="button amazon" disabled aria-describedby="amazon-note">Order on Amazon</button>`;
 const note=p.packConflict?'The matching pack is awaiting confirmation on Amazon. You can order this pack on Fashinoworld.':'An Amazon link for this pack is not available yet. You can order it on Fashinoworld.';
 const gallery=`<div class="product-gallery"><div class="main-product-image${cleanImages.has(p.id)||p.id==='TB-05'?' clean':''}"><img id="main-product-photo" src="${p.image}" alt="TreeBites ${esc(p.name)} product packaging" width="1000" height="1000" fetchpriority="high"></div>${p.image!==p.alternate?`<div class="thumbnails" aria-label="Product images"><button class="thumbnail selected" data-image="${p.image}" aria-label="Show product packaging" aria-pressed="true"><img src="${p.image}" alt="" width="80" height="80"></button><button class="thumbnail" data-image="${p.alternate}" aria-label="Show brand product information" aria-pressed="false"><img src="${p.alternate}" alt="" width="80" height="80"></button></div>`:''}<p class="image-caption">TreeBites product imagery · Packaging may vary.</p></div>`;
 const body=`<div class="product-breadcrumbs breadcrumbs"><a href="/">Home</a><span>/</span><a href="/categories/${p.category.slug}/">${esc(p.category.name)}</a><span>/</span><span>${esc(p.name)}</span></div><section class="product-detail">${gallery}<div class="product-info"><a class="eyebrow category-label" href="/categories/${p.category.slug}/">${esc(p.category.name)}</a><h1>${esc(p.name)}</h1><p class="product-description">${esc(p.description)}</p>${variants}<div class="buy-panel"><span class="eyebrow">CHOOSE WHERE TO ORDER</span><div class="purchase-buttons">${amazon}<a class="button" href="${esc(p.fashinoworld.variantUrl||p.fashinoworld.url)}" target="_blank" rel="noopener noreferrer">Buy now<span class="sr-only"> at Fashinoworld (opens in a new tab)</span></a></div><p class="retailer-help">Website orders open on Fashinoworld. Check your retailer for current price, delivery and availability.</p>${!p.amazonURL?`<p class="availability-note" id="amazon-note">${note}</p>`:''}</div><div class="product-accordions"><details><summary>Product details</summary><dl class="product-facts"><dt>Brand</dt><dd>TreeBites</dd><dt>Pack size</dt><dd>${esc(p.size)}</dd><dt>Product code</dt><dd>${esc(p.fashinoworld.sku||p.id)}</dd><dt>Category</dt><dd>${esc(p.category.name)}</dd></dl></details><details open><summary>${p.category.slug==='supplements-and-fibre'?'Directions & care':'Enjoy it your way'}</summary><p>${esc(p.use)}</p></details><details><summary>Ingredients & product information</summary><p>Refer to the product packaging and the retailer’s listing for the complete ingredients, allergens, nutrition information and best-before date.${p.id==='TB-17'?' This product contains milk.':''}${p.id==='TB-05'?' This blend contains sesame.':''}</p></details><details><summary>Delivery & returns</summary><p>Your chosen retailer handles payment, delivery and returns. Check their product page for delivery to your address and their applicable policies.</p></details></div></div></section><section class="section related-section"><div class="section-heading"><div><span class="eyebrow">KEEP EXPLORING</span><h2>A little more goodness.</h2></div><a class="text-link" href="/products/">View all products</a></div><div class="product-grid featured-grid">${relatedFinal.map(card).join('')}</div></section>`;
 write(`products/${p.slug}`,layout(p.name,p.description,body,'products'));
}
fs.writeFileSync(path.join(out,'404.html'),seo.decorate(addStyles(layout('Page not found','Find your way back to the TreeBites collection.',`<section class="section not-found"><span class="eyebrow">404 · PAGE NOT FOUND</span><h1>Let’s get back<br>to the good things.</h1><p>The page you’re looking for may have moved.</p><a class="button" href="/products/">Explore our products</a></section>`)), '/404.html',{notFound:true}));
write('sitemap',layout('Sitemap','Explore every TreeBites category and product page from one accessible index.',`<section class="collection-top"><div class="breadcrumbs"><a href="/">Home</a><span>/</span><span>Sitemap</span></div><span class="eyebrow">THE WHOLE TREEBITES FAMILY</span><h1>Every kind of good.</h1><p>Find every category and product in the TreeBites collection.</p></section><section class="section sitemap-groups"><div class="sitemap-group"><h2>Explore TreeBites</h2><a href="/">Home</a><a href="/products/">All products</a><a href="/categories/">Categories</a><a href="/our-story/">Our story</a><a href="/#questions">Questions & answers</a></div>${categories.map(c=>`<div class="sitemap-group"><h2><a href="/categories/${c.slug}/">${esc(c.name)}</a></h2>${products.filter(p=>p.category.slug===c.slug).map(p=>`<a href="/products/${p.slug}/">${esc(p.name)} · ${esc(p.size)}</a>`).join('')}</div>`).join('')}</section>`));
seo.writeDiscoveryFiles();
fs.writeFileSync(path.join(root,'src/catalogue.json'),JSON.stringify(products.map(p=>({id:p.id,name:p.name,slug:p.slug,category:p.category.name,size:p.size,website:p.fashinoworld.variantUrl||p.fashinoworld.url,amazon:p.amazonURL,amazonResearch:p.amazon.url,amazonStatus:p.packConflict?'blocked_pack_conflict':p.amazon.matchStatus,image:p.image})),null,2));
// Keep the editable website in the opened folder and export a hosting copy.
// Remove only the retired generated page; retained research/images are untouched.
for(const relative of ['products/nolen-gur-two-pack/index.html','dist/products/nolen-gur-two-pack/index.html']){
 fs.rmSync(path.join(root,relative),{force:true});
}
const publishDirectory=path.join(root,'dist');
fs.mkdirSync(publishDirectory,{recursive:true});
for(const entry of ['index.html','404.html','robots.txt','sitemap.xml','sitemap','llms.txt','llms-full.txt','catalogue.json','_headers','_redirects','assets','products','categories','our-story']){
 fs.cpSync(path.join(root,entry),path.join(publishDirectory,entry),{recursive:true});
}
console.log(`Generated ${4+categories.length+1+products.length} pages in the opened folder and exported dist/. ${products.length} products. ${products.filter(p=>p.amazonURL).length} enabled Amazon links; ${products.filter(p=>!p.amazonURL).length} safely held for verification.`);
